### ISSUE TITLE
Related address  and port

### ISSUE THREAD

**Issue by misi** [ObserveRTC/schemas#1]
In W3C API the discovered local candidates don't have the related address(raddr) and port(rport) 
But could be parsed from sdp. e.g.
`a=candidate:2 1 UDP 1694498815 192.0.2.3 45664 typ srflx raddr 10.0.1.1 rport 8998`
It could give some insight what is the default route (lan/wifi/mobile) and may could help detect debugging roaming issues.

**Comment by balazskreith** [comment]
Should we add a new field to the ClientSample as `localSdp: string[]` ? The server can parse and do necessary stuff with it

**Comment by balazskreith** [comment]
8fe06243ebce8574271c77acfafde4dda458e757
